depService:
  rds:
    admin_key: "U1lTREJBOlNZU0RCQTAwMQ=="
    host: "10.4.110.98"
    port: 5236
    username: "SYSDBA"
    password: "SYSDBA001"
    type: "DM8"
    source_type: "external"
    mgmt_host: "mariadb-mgmt-cluster.resource"
    mgmt_port: 8888
    system_id: ""

  # mongodb
  mongodb:
    host: "127.0.0.1,127.0.0.1,127.0.0.1"
    port: 28000
    user: ""
    db: "anyshare"
    password: ""
    replicaSet: "emetadata"
    mgmt_host: "proton-mongodb-mgmt.resource"
    mgmt_port: 28001
    admin_key: "cm9vdDplaXNvby5jb20xMjM="
    options: {}
    source_type: "external"

  # redis
  redis:
    connectInfo:
      username: "root"
      password: "eisoo.com123"
      host: ""
      port: 26379
      masterHost: ""
      masterPort: 26379
      slaveHost: ""
      slavePort: 26379
      sentinelHost: "proton-redis-proton-redis-sentinel.resource.svc.cluster.local"
      sentinelPort: 26379
      sentinelUsername: "root"
      sentinelPassword: "eisoo.com123"
      masterGroupName: "mymaster"
    connectType: "sentinel"


config:
  # other
  script_directory_path: "/tmp/pycharm_project_201/dataModelManagement/test/"
  env_mode: "dev"
  log_level: "INFO"
  mode: normal
  online_upgrade: "true"
  stage: "pre"
  #logLevel: "INFO"
  #
  #mode: "normal"
  #
  #onlineUpgrade: true
  #
  #stage: "pre"

databases:
  - "test03"
  - "test01"

renamed_services:
  - old_name: test01
    new_name: test02

#databases:
#  - "user_management"
#  - "anyshare"
#  - "policy_mgnt"
#  - "privacy"
#  - "authentication"
#  - "eofs"
#  - "deploy"
#  - "sharemgnt_db"
#  - "ets"
#  - "ossmanager"
#  - "license"
#  - "nodemgnt"
#  - "sites"
#  - "anydata"
#  - "third_app_mgnt"
#  - "hydra_v2"


