# Default values for dm-pre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: dip
moduleName: dm-pre

# 环境变量：语言/时区
env:
  timezone: Asia/Shanghai
  language: en_US.UTF-8

replicaCount: 1

# 节点选择器
nodeSelector: {}

image:
  registry: acr.aishu.cn
  repository: dip/dm
  tag: tag
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: true
  runAsUser: 5000
  runAsGroup: 5000

resources: {}
#  limits:
#    cpu: 200m
#    memory: 500Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

activeDeadlineSeconds: 3600

backoffLimit: 0

restartPolicy: Never

scriptDirectoryPath: /app/repos/

envMode: LIVE

logLevel: INFO

mode: normal

onlineUpgrade: "true"

stage: pre

depServices:
  rds:
    source_type: internal
    type: MariaDB
    host: mariadb-mariadb-master.resource.svc.cluster.local.
    port: 3330
    user: anyshare
    password: eisoo.com123
    hostRead: mariadb-mariadb-cluster.resource.svc.cluster.local.
    portRead: 3330
    admin_key: "cm9vdDplaXNvby5jb20xMjM="
    mgmt_host: mariadb-mgmt-cluster.resource.svc.cluster.local.
    mgmt_port: 8888
    system_id: ""
  opensearch:
    host: opensearch-master.resource.svc.cluster.local.
    port: 9200
    protocol: http
    user: admin
    password: eisoo.com123