apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.moduleName }}-job
  namespace: {{ .Values.namespace }}
  annotations:
    module: {{ .Values.moduleName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: "10"
spec:
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      labels:
        module: {{ .Values.moduleName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      containers:
        - name: {{ .Values.moduleName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "dm-post.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: {{ .Values.env.timezone | quote }}
            - name: LANG
              value: {{ .Values.env.language | quote }}
          {{- if and .Values.depServices .Values.depServices.rds .Values.depServices.rds.type }}
            - name: DB_TYPE
              value: {{ index .Values "depServices" "rds" "type" | default "MariaDB" | quote }}
          {{- end }}
          {{- if and .Values.depServices .Values.depServices.mq .Values.depServices.mq.mqType }}
            - name: MQ_TYPE
              value: {{ index .Values "depServices" "mq" "mqType" | default "kafka" | quote }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.moduleName }}-secret
              mountPath: /etc/DataModelManagement/secret.yaml
              subPath: {{ .Values.moduleName }}-secret.yaml
      volumes:
        - name: {{ .Values.moduleName }}-secret
          secret:
            secretName: {{ .Values.moduleName }}-secret
      restartPolicy: {{ .Values.restartPolicy }}
