apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moduleName }}-secret
  namespace: {{ .Values.namespace }}
  annotations:
    module: {{ .Values.moduleName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: "1"
stringData:
  {{ .Values.moduleName }}-secret.yaml: |

    config:
      timezone: {{ .Values.env.timezone | quote }}
      env_language: {{ .Values.env.language | quote }}

      script_directory_path: {{ index .Values "scriptDirectoryPath" | quote }}
      env_mode: {{ index .Values "envMode" | quote }}
      log_level: {{ index .Values "logLevel" | quote }}
      mode: {{ index .Values "mode" | quote }}
      online_upgrade: {{ index .Values "onlineUpgrade" | quote }}
      stage: {{ index .Values "stage" | quote }}

    DATABASES:
      - "deploy"

    depServices:
{{ .Values.depServices | toYaml | indent 6 }}
